name: deploy to dev cluster
on:
  push:
    branches:
      - "master"

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.HARSHMAX_PEM }}" > ~/harshmax.pem
          chmod 600 ~/harshmax.pem
          
      - name: Upload .env securely
        run: |
          echo "Uploading .env file..."
          echo "${{ secrets.ENV }}" | base64 -w 0 | ssh -i ~/harshmax.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.DEV_SERVER_IP }} "base64 -d > /home/ubuntu/paisafy-server/.env"

      - name: Redeploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/harshmax.pem ubuntu@${{ secrets.DEV_SERVER_IP }} << EOF
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
            export PATH=\$PATH:/home/ubuntu/.npm-global/bin
            cd /home/ubuntu/paisafy-server
            git pull origin master
            pnpm install
            pnpm run build
            pm2 restart pbs
          EOF